/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-02-02 10:36:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.signUp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>新規会員登録</title>\r\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js\" type=\"text/javascript\" ></script>\r\n");
      out.write("<link href=\"/ChatSystem/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/ChatSystem/css/bootstrap-responsive.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"/ChatSystem/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("<!-- エラー表示 -->\r\n");
      out.write("      <div class=\"bs-docs-section\">\r\n");
      out.write("\t\t       <div class=\"row\">\r\n");
      out.write("\t\t         <div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t       　　　　　</div>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("<!--END エラー表示 -->\r\n");
      out.write("\r\n");
      out.write("      <!-- Forms\r\n");
      out.write("      ================================================== -->\r\n");
      out.write("      <div class=\"bs-docs-section\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-12\">\r\n");
      out.write("            <div class=\"page-header\">\r\n");
      out.write("              <h2 id=\"forms\">会員情報一覧</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-6\">\r\n");
      out.write("            <div class=\"well bs-component\">\r\n");
      out.write("              <form action=\"/ChatSystem/loginout/accountManager\" method=\"post\" class=\"form-horizontal\">\r\n");
      out.write("                <fieldset>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"inputEmail\" class=\"col-lg-2 control-label\">アカウント名</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                      <input type=\"text\" name=\"name\" class=\"form-control\" id=\"inputEmail\" placeholder=\"アカウント名を入力してください\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"inputEmail\" class=\"col-lg-2 control-label\">メールアドレス</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                      <input type=\"text\" name=\"mail\" class=\"form-control\" id=\"inputEmail\" placeholder=\"メールアドレスを入力してください\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"inputEmail\" class=\"col-lg-2 control-label\">パスワード</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                      <input type=\"password\" name=\"pass\" class=\"form-control\" id=\"inputEmail\" placeholder=\"パスワードを入力してください\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"select\" class=\"col-lg-2 control-label\">都道府県</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t<select name=\"prefecture\"class=\"form-control\" id=\"select\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">都道府県をお選びください。</option>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"北海道・東北\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"北海道\">北海道</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"青森県\">青森県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"岩手県\">岩手県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"宮城県\">宮城県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"秋田県\">秋田県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"山形県\">山形県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"福島県\">福島県</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"関東\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"茨城県\">茨城県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"栃木県\">栃木県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"群馬県\">群馬県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"埼玉県\">埼玉県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"千葉県\">千葉県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"東京都\">東京都</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"神奈川県\">神奈川県</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"甲信越・北陸\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"新潟県\">新潟県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"富山県\">富山県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"石川県\">石川県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"福井県\">福井県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"山梨県\">山梨県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"長野県\">長野県</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"東海\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"岐阜県\">岐阜県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"静岡県\">静岡県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"愛知県\">愛知県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"三重県\">三重県</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"関西\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"滋賀県\">滋賀県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"京都府\">京都府</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"大阪府\">大阪府</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"兵庫県\">兵庫県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"奈良県\">奈良県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"和歌山県\">和歌山県</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"中国\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"鳥取県\">鳥取県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"島根県\">島根県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"岡山県\">岡山県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"広島県\">広島県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"山口県\">山口県</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"四国\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"徳島県\">徳島県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"香川県\">香川県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"愛媛県\">愛媛県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"高知県\">高知県</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"九州・沖縄\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"福岡県\">福岡県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"佐賀県\">佐賀県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"長崎県\">長崎県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"熊本県\">熊本県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"大分県\">大分県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"宮崎県\">宮崎県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"鹿児島県\">鹿児島県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"沖縄県\">沖縄県</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"inputEmail\" class=\"col-lg-2 control-label\">電話番号</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\" id=\"inputEmail\" placeholder=\"電話番号を入力してください\" name=\"tel\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"inputEmail\" class=\"col-lg-2 control-label\">年齢</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\" id=\"inputEmail\" placeholder=\"年齢を入力してください\" name=\"age\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"col-lg-10 col-lg-offset-2\">\r\n");
      out.write("                      <button class=\"btn btn-default\" type=\"reset\">リセットする</button>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"accountManage\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"method\" value=\"register\">\r\n");
      out.write("                      <button type=\"submit\" class=\"btn btn-primary\">登録する</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </fieldset>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("         </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t<p><a href=\"/ChatSystem/loginout/reload\">ログインする</a></p>\r\n");
      out.write("\t\r\n");
      out.write("</div>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /signUp/index.jsp(21,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error.message != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t            <div class=\"bs-component\">\r\n");
        out.write("\t\t\t              <div class=\"alert alert-dismissable alert-danger\">\r\n");
        out.write("\t\t\t                <button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\r\n");
        out.write("\t\t\t\t\t\t\t\t<h4>Warning!</h4>\r\n");
        out.write("\t\t\t\t\t\t\t\t<p>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error.message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</p>\r\n");
        out.write("\t\t\t              </div>\r\n");
        out.write("\t\t\t            </div>\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
