/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-01-30 09:37:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>マイページ</title>\r\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js\" type=\"text/javascript\" ></script>\r\n");
      out.write("<link href=\"/ChatSystem/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/ChatSystem/css/bootstrap-responsive.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"/ChatSystem/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- ナビ -->\r\n");
      out.write("   <div class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <a href=\"/ChatSystem/chat/chatList\" class=\"navbar-brand\">ChatSystem</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"navbar-collapse collapse\" id=\"navbar-main\">\r\n");
      out.write("          <ul class=\"nav navbar-nav\">\r\n");
      out.write("            <li>\r\n");
      out.write("            \t<a href=\"/ChatSystem/loginout/logout\">ログアウト</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("<!--END ナビ -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("<!-- ステータス -->\r\n");
      out.write("      <div class=\"page-header\" id=\"banner\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\t<!-- お知らせ表示 -->\r\n");
      out.write("\t\t<!-- エラーメッセージ -->\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t<!--END エラーメッセージ -->\r\n");
      out.write("\t\t<!-- お知らせその2　実行結果 -->\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t<!--END お知らせその2　実行結果 -->\r\n");
      out.write("\t<!--END お知らせ表示 -->\r\n");
      out.write("<!--END ステータス -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-sm-3\"><!-- 左カラム -->\r\n");
      out.write("   <div class=\"panel panel-default\">\r\n");
      out.write("    <div class=\"panel-body\">\r\n");
      out.write("<!-- フレンドリスト -->\r\n");
      out.write("\t<!-- 友達一覧 -->\r\n");
      out.write("\t      <!-- Tables\r\n");
      out.write("\t      ================================================== -->\r\n");
      out.write("\t      <div class=\"bs-docs-section\">\r\n");
      out.write("\t\r\n");
      out.write("\t          <div class=\"col-lg-12\">\r\n");
      out.write("\t            <div class=\"page-header\">\r\n");
      out.write("\t              <h2 id=\"tables\">友達一覧</h2>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t\r\n");
      out.write("\t            <div class=\"bs-component\">\r\n");
      out.write("\t           \t<form action=\"/ChatSystem/chat/friendsList\" method=\"post\">\r\n");
      out.write("\t              <table class=\"table table-striped table-hover \">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>友達名</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>ステータス</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t   </div>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<!--END 友達一覧 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 友達リクエスト一覧 -->\r\n");
      out.write("\t\t      <!-- Tables\r\n");
      out.write("\t\t      ================================================== -->\r\n");
      out.write("\t\t      <div class=\"bs-docs-section\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t          <div class=\"col-lg-12\">\r\n");
      out.write("\t\t            <div class=\"page-header\">\r\n");
      out.write("\t\t              <h2 id=\"tables\">友達リクエスト一覧</h2>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t            <div class=\"bs-component\">\r\n");
      out.write("\t\t\t\t\t  <form action=\"/ChatSystem/chat/friendsRequestList\" method=\"post\">\r\n");
      out.write("\t\t              <table class=\"table table-striped table-hover \">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>友達名</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>ステータス</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t \t\t\t\t  </table>\r\n");
      out.write("\t\t\t\t\t  </form>\r\n");
      out.write("\t\t\t\t　　　</div>\t\r\n");
      out.write("\t\t\t　　　　　</div>\t\r\n");
      out.write("\t　　　　　\t　　</div>\t\r\n");
      out.write("\t<!--END 友達リクエスト一覧 -->\r\n");
      out.write("<!--END　フレンドリスト -->\r\n");
      out.write("    </div>\r\n");
      out.write("   </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-sm-6\"><!-- 中心カラム -->\r\n");
      out.write("   <div class=\"panel panel-default\">\r\n");
      out.write("    <div class=\"panel-body\">\r\n");
      out.write("<!-- 会員情報一覧 -->\r\n");
      out.write("      <!-- Forms\r\n");
      out.write("      ================================================== -->\r\n");
      out.write("      <div class=\"bs-docs-section\">\r\n");
      out.write("          <div class=\"col-lg-12\">\r\n");
      out.write("            <div class=\"page-header\">\r\n");
      out.write("              <h2 id=\"forms\">会員情報</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-12\">\r\n");
      out.write("            <div class=\"well bs-component\">\r\n");
      out.write("              <form class=\"form-horizontal\" action=\"/ChatSystem/chat/accountManage\" method=\"post\">\r\n");
      out.write("                <fieldset>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"inputEmail\" class=\"col-lg-2 control-label\">名前</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("\t                  <input type=\"text\" class=\"form-control\" id=\"inputEmail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${accountAllInfo.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled=\"disabled\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <label for=\"inputEmail\" class=\"col-lg-2 control-label\">新しいパスワード</label>\r\n");
      out.write("                   <div class=\"col-lg-10\">\r\n");
      out.write("                     <input type=\"text\" class=\"form-control\" id=\"inputEmail\" placeholder=\"パスワードを変更する場合は入力してください\" name=\"newPass1\">\r\n");
      out.write("                   </div>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\" id=\"inputEmail\" placeholder=\"再度パスワードを入力\" name=\"newPass2\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"inputEmail\" class=\"col-lg-2 control-label\">メールアドレス</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\" id=\"inputEmail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${accountAllInfo.mail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"mail\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"select\" class=\"col-lg-2 control-label\">都道府県</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t<select name=\"prefecture\"class=\"form-control\" id=\"select\">\r\n");
      out.write("\t\t\t\t\t\t<option selected value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${accountAllInfo.prefecture}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${accountAllInfo.prefecture}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"北海道・東北\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"北海道\">北海道</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"青森県\">青森県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"岩手県\">岩手県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"宮城県\">宮城県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"秋田県\">秋田県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"山形県\">山形県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"福島県\">福島県</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"関東\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"茨城県\">茨城県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"栃木県\">栃木県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"群馬県\">群馬県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"埼玉県\">埼玉県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"千葉県\">千葉県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"東京都\">東京都</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"神奈川県\">神奈川県</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"甲信越・北陸\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"新潟県\">新潟県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"富山県\">富山県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"石川県\">石川県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"福井県\">福井県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"山梨県\">山梨県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"長野県\">長野県</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"東海\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"岐阜県\">岐阜県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"静岡県\">静岡県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"愛知県\">愛知県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"三重県\">三重県</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"関西\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"滋賀県\">滋賀県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"京都府\">京都府</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"大阪府\">大阪府</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"兵庫県\">兵庫県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"奈良県\">奈良県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"和歌山県\">和歌山県</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"中国\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"鳥取県\">鳥取県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"島根県\">島根県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"岡山県\">岡山県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"広島県\">広島県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"山口県\">山口県</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"四国\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"徳島県\">徳島県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"香川県\">香川県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"愛媛県\">愛媛県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"高知県\">高知県</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t<optgroup label=\"九州・沖縄\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"福岡県\">福岡県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"佐賀県\">佐賀県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"長崎県\">長崎県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"熊本県\">熊本県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"大分県\">大分県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"宮崎県\">宮崎県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"鹿児島県\">鹿児島県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"沖縄県\">沖縄県</option>\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"inputEmail\" class=\"col-lg-2 control-label\">電話番号</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\" id=\"inputEmail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${accountAllInfo.tel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"tel\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"inputEmail\" class=\"col-lg-2 control-label\">年齢</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\" id=\"inputEmail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${accountAllInfo.age}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"age\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"inputEmail\" class=\"col-lg-2 control-label\">閲覧用URL</label>\r\n");
      out.write("                    <div class=\"col-lg-10\">\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\" id=\"inputEmail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${accountAllInfo.url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"accountUrl\">\r\n");
      out.write("                    <span class=\"help-block\">\r\n");
      out.write("                    \t<a href=\"http://testserver.weserve.co.jp/ChatSystem/read/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${accountAllInfo.url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" >http://testserver.weserve.co.jp/ChatSystem/read/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${accountAllInfo.url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</a><br />\r\n");
      out.write("                    </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"col-lg-10 col-lg-offset-2\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"accountId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${accountAllInfo.accountId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"method\" value=\"modify\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">変更する</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </fieldset>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("<!--END 会員情報一覧 -->\r\n");
      out.write("\t </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-sm-3\"><!-- 右カラム -->\r\n");
      out.write("   <div class=\"panel panel-default\">\r\n");
      out.write("    <div class=\"panel-body\">\r\n");
      out.write("<!-- 参加中のチャット -->\r\n");
      out.write("      <!-- Tables\r\n");
      out.write("      ================================================== -->\r\n");
      out.write("      <div class=\"bs-docs-section\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-12\">\r\n");
      out.write("            <div class=\"page-header\">\r\n");
      out.write("              <h2 id=\"tables\">参加中のチャット</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"bs-component\">\r\n");
      out.write("              <table class=\"table table-striped table-hover \">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>ルームNo</th>\r\n");
      out.write("\t\t\t\t\t<th>ルーム名</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("<!--END 参加中のチャット -->\r\n");
      out.write("  　　　</div>\r\n");
      out.write("  　　</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/jsp/myPage.jsp(42,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error.message != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t<div class=\"bs-component\">\r\n");
        out.write("\t\t\t\t\t<div class=\"alert alert-dismissable alert-danger\">\r\n");
        out.write("\t\t\t\t\t  <button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\r\n");
        out.write("\t\t\t\t\t\t\t<h4>Warning!</h4>\r\n");
        out.write("\t\t\t\t\t\t\t<p>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error.message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</p>\r\n");
        out.write("\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t</div>\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/jsp/myPage.jsp(53,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result !=null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t<div class=\"bs-component\">\r\n");
        out.write("\t\t\t\t\t<div class=\"alert alert-dismissable alert-info\">\r\n");
        out.write("\t\t\t\t\t  <button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\r\n");
        out.write("\t\t\t\t\t\t<h4>Info</h4>\r\n");
        out.write("\t\t\t\t\t\t<p>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</p>\r\n");
        out.write("\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t</div>\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/jsp/myPage.jsp(88,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("friendsList");
    // /WEB-INF/jsp/myPage.jsp(88,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/myPage.jsp(88,5) '${friendsList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${friendsList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${friendsList.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("さん</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t<td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"method\" value=\"remove\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\" name=\"friendsAccountId\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${friendsList.accountId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"btn btn-primary\">フォローを解除します</button>\r\n");
          out.write("\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t</tr>\t\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /WEB-INF/jsp/myPage.jsp(121,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("friendsRequestList");
    // /WEB-INF/jsp/myPage.jsp(121,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/myPage.jsp(121,5) '${friendsRequestList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${friendsRequestList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${friendsRequestList.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("さん</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t<td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"method\" value=\"modify\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\" name=\"friendsAccountId\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${friendsRequestList.accountId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"btn btn-primary\">承認する</button>\r\n");
          out.write("\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t</tr>\t\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /WEB-INF/jsp/myPage.jsp(308,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("joinChatRoomList");
    // /WEB-INF/jsp/myPage.jsp(308,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/myPage.jsp(308,4) '${joinChatRoomList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${joinChatRoomList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${joinChatRoomList.chatId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t<td><a href=\"/ChatSystem/chat/chatRoom?chatId=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${joinChatRoomList.chatId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${joinChatRoomList.roomName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a></td>\r\n");
          out.write("\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }
}
